name: Playwright P2 Tests
on:
  schedule:
    # Run every day at 14:28 UTC
    - cron: "28 14 * * *"
  workflow_dispatch: # This line allows manual triggering of the workflow

jobs:
  test:
    timeout-minutes: 60
    # Using ubuntu-22.04 for Playwright compatibility
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Cache Camoufox browser
        uses: actions/cache@v4.2.3
        with:
          path: ~/.cache/camoufox
          key: camoufox-browser-${{ hashFiles('package-lock.json') }}
      - name: Install system dependencies
        run: npx playwright install-deps
      - name: Install Camoufox browser
        run: npx camoufox-js fetch
      - name: Run Playwright tests
        env:
          FIRST_NAME: ${{ secrets.FIRST_NAME_P2 }}
          LAST_NAME: ${{ secrets.LAST_NAME_P2 }}
          NUMBER_OF_TICKETS: ${{ secrets.NUMBER_OF_TICKETS }}
          EMAIL: ${{ secrets.EMAIL_P2 }}
          DOB_MONTH: ${{ secrets.DOB_MONTH_P2 }}
          DOB_DAY: ${{ secrets.DOB_DAY_P2 }}
          DOB_YEAR: ${{ secrets.DOB_YEAR_P2 }}
          ZIP: ${{ secrets.ZIP_P2 }}
          COUNTRY: ${{ secrets.COUNTRY }}
        run: xvfb-run npx playwright test
      - uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: playwright-report-p2
          path: playwright-report/
          retention-days: 7
      - uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: screenshots-p2
          path: screenshots/
          retention-days: 7
