name: Playwright Tests
on:
  schedule:
    # Run every day at 14:23 UTC
    - cron: "23 14 * * *"
  workflow_dispatch: # This line allows manual triggering of the workflow

jobs:
  test:
    timeout-minutes: 60
    # Using ubuntu-22.04 for Playwright compatibility
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-node@v4.4.0
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install Camoufox browser
        run: npx camoufox-js fetch
      - name: Cache Playwright browsers
        uses: actions/cache@v4.2.3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ hashFiles('package-lock.json') }}
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          FIRST_NAME: ${{ secrets.FIRST_NAME }}
          LAST_NAME: ${{ secrets.LAST_NAME }}
          NUMBER_OF_TICKETS: ${{ secrets.NUMBER_OF_TICKETS }}
          EMAIL: ${{ secrets.EMAIL }}
          DOB_MONTH: ${{ secrets.DOB_MONTH }}
          DOB_DAY: ${{ secrets.DOB_DAY }}
          DOB_YEAR: ${{ secrets.DOB_YEAR }}
          ZIP: ${{ secrets.ZIP }}
          COUNTRY: ${{ secrets.COUNTRY }}
        run: xvfb-run npx playwright test
      - uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
      - uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: screenshots
          path: screenshots/
          retention-days: 7
